spring:
  sql:
    init:
      platform: postgres

  jpa:
    hibernate:
      ddl-auto: update

  messages:
    basename: errorMessage
    encoding: utf-8

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never

logging:
  file:
    name: ./logs/saveur_solidaire.log

springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dev_saveur_solidaire
    username: saveur_solidaire_user
    password: Xb3r7z5v

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prod_saveur_solidaire
    username: saveur_solidaire_user
    password: Xb3r7z5v

  jpa:
    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          format_sql: false
          show_sql: false
          temp:
            use_jdbc_metadata_defaults: false

server:
  port: 8090


