name: Deploy Saveur Solidaire API to Production
on:
  push: 
    tags:
      - 'v*'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -Dspring.profiles.active=prod

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: saveur-solidaire-api.jar
          path: target/*.jar
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download jar Artifact
        uses: actions/download-artifact@v2
        with:
          name: saveur-solidaire-api.jar
          path: ./target/

      - name: Deploy to Server
        uses: i3h/deploy-with-scp@v1
        with:
          server-ip: ${{ secrets.SERVER_IP_PROD }}
          username: ${{ secrets.SERVER_USERNAME }}
          ssh-key: ${{ secrets.SERVER_SSH_KEY }}
          src: ./target/saveur-solidaire-api.jar
          dest: /home/${{ secrets.SERVER_USERNAME }}/saveur-solidaire-api/git-deployments/saveur-solidaire-api-${{ github.ref_name }}.jar